dist: trusty
language: java
jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      install: "./gradlew jar"
      script: skip
    - stage: test
      jdk: oraclejdk8
      install: skip
      script: "./gradlew check"
    - stage: test
      jdk: oraclejdk9
      install: skip
      script: "./gradlew check"
    - stage: test
      jdk: oraclejdk11
      install: skip
      script: "./gradlew check"
    - stage: test
      jdk: openjdk8
      install: skip
      script: "./gradlew check"
stages:
  - build
  - test
