name: Build
on:
  push:
jobs:

  build:
    name: Project build and analysis
    runs-on: ubuntu-latest
    steps:

      - name: Project checkout
        uses: actions/checkout@v3
        with:
          # shallow clone disabled for a better relevancy of Sonar analysis
          fetch-depth: 0

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle setup
        uses: gradle/gradle-build-action@v2

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Artifact creation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew jar jacocoTestReport sonarqube
